/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Boi(props) {
    const { nodes, materials } = useGLTF("3d/boi.gltf");
    return (
        <group {...props} dispose={null} position={[0,-1.5,0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} >
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.body_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.body_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[375.47, 427.95, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={62.4}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                    </group>
                    <group
                        position={[375.47, 427.95, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={60.32}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere001_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[-357.4, 392.65, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={39.71}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere002_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere002_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[-357.4, 392.65, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={41.07}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere003_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[-341.99, 460.2, -117.03]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={62.4}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere005_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                    </group>
                    <group
                        position={[-341.99, 460.2, -117.03]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={60.32}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere006_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[199.63, 566.88, -221]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={39.71}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere007_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere007_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[199.63, 566.88, -221]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={41.07}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere008_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 1.89]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.waves_Material002_0.geometry}
                            material={materials["Material.002"]}
                            scale={0.34}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 1.89]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.waves1_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[92.46, 15.53, 2.11]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 1.89]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.waves2_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("3d/boi.gltf");
